server.port=8888

#eureka config
eureka.client.service-url.defaultZone=http://${EUREKA_IP:localhost}:${EUREKA_PORT:9999}/eureka

#microservice routes

#pet http://ip:8888/pets
spring.cloud.gateway.server.webflux.routes[0].id=microservicepet
spring.cloud.gateway.server.webflux.routes[0].uri=lb://microservicepet
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/pets/**

#adopter http://ip:8888/adopters
spring.cloud.gateway.server.webflux.routes[1].id=microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].uri=lb://microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/adopters/**

#adoption request http://ip:8888/adoptions
spring.cloud.gateway.server.webflux.routes[2].id=microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].uri=lb://microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/adoptions/**